#!/bin/sh

USAGE='[OPTION]... init [--force] [--aether] module'
DESCRIPTION='Creates an OpenShift environment for your module'
LONG_USAGE='    ceylon openshift

Run with:

    ceylon openshift init module

OPTIONS

--help
    Print this help message.
    (--help=options prints help for the various options.)

--force
    Overwrite openshift files even if they already exist.

--aether
    Add the `enable_aether` marker (required if your application uses Maven modules).

'

. $CEYLON_HOME/bin/ceylon-sh-setup

$CEYLON run --run ceylon.openshift.cli::run ceylon.openshift/1.2.2 "$@"
